### ISSUE TITLE
Set CNAME file

### ISSUE THREAD

**Issue by Beanow** [tauri-apps/tauri.studio#2]
From https://github.com/tauri-apps/tauri-apps.org/pull/1#issuecomment-531497262
> Please be sure to commit / generate a file `/docs/CNAME` containing `tauri-apps.org`.
> As per [this doc](https://help.github.com/en/articles/configuring-a-publishing-source-for-github-pages#publishing-your-github-pages-site-from-a-docs-folder-on-your-master-branch) it should be in the folder not root of the master branch.

**Comment by nothingismagick** [comment]
Resolved here: https://github.com/tauri-apps/tauri-apps.org/commit/df56a2be865cb0a9891cd704b68a9ffd74391bf1
